/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_zhihu_activity_c_API */

#ifndef _Included_com_android_zhihu_activity_c_API
#define _Included_com_android_zhihu_activity_c_API
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_zhihu_activity_c_API
 * Method:    getThemesUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_1zhihu_activity_c_API_getThemesUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_android_zhihu_activity_c_API
 * Method:    getStartImageUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_1zhihu_activity_c_API_getStartImageUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_android_zhihu_activity_c_API
 * Method:    getLatestUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_1zhihu_activity_c_API_getLatestUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_android_zhihu_activity_c_API
 * Method:    getBefore
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_1zhihu_activity_c_API_getBefore
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
